[package]
name = "terminal-raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive"] }
pollster = "0.4.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu = "25.0.2"
crossterm = "0.29.0"
