name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: terminal-raytracer-linux
          - os: macos-latest
            asset_name: terminal-raytracer-macos
          - os: windows-latest
            asset_name: terminal-raytracer-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary (Unix)
        if: runner.os != 'Windows'
        run: mv target/release/terminal-raytracer target/release/${{ matrix.asset_name }}

      - name: Rename binary (Windows)
        if: runner.os == 'Windows'
        run: mv target/release/terminal-raytracer.exe target/release/${{ matrix.asset_name }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
